-- -----------------------------------------------------------------------------
-- kgi-ggreport-web — MySQL 미러 (002) : 삽입 순서 컬럼 SEQ_NO
--                                        ※ 외부망 로컬(out-local) 전용
--
-- ⚠️ 이 파일은 **정본이 아니다.** 정본은 db/oracle/002_seq_no.sql 이고, 왜 이 컬럼이
--    필요한지(SQLite `rowid` 의존 SQL 8곳)와 버린 대안은 거기에 적혀 있다.
--    정본이 바뀌면 같은 커밋에서 이 파일도 바꾼다.
--
-- Oracle `GENERATED BY DEFAULT AS IDENTITY` ↔ MySQL `AUTO_INCREMENT`.
-- 둘 다 "INSERT 에서 컬럼을 생략하면 DB 가 단조 증가값을 채운다"라서 **Mapper XML 이
-- 한 벌로 끝난다**(databaseIdProvider 불필요).
--
-- ⚠️ MySQL 은 AUTO_INCREMENT 컬럼이 **키의 일부여야 한다**(ERROR 1075). 그래서
--    UNIQUE KEY 를 같은 ALTER 문 안에서 함께 추가한다 — 두 문장으로 나누면 첫
--    문장이 실패한다.
--
-- ⚠️ 001 과 달리 이 스크립트는 **멱등하지 않다.** MySQL 8.0 에는
--    `ADD COLUMN IF NOT EXISTS` 가 없다(MariaDB 확장이다). 두 번 돌리면
--    ERROR 1060 (Duplicate column name) 이 난다 — 정본(Oracle)과 같은 성질이라
--    "번호 붙은 스크립트를 한 번씩 적용한다"는 규칙(설계 §5-D)은 그대로다.
-- -----------------------------------------------------------------------------

ALTER TABLE BID_CASES
    ADD COLUMN SEQ_NO BIGINT NOT NULL AUTO_INCREMENT,
    ADD UNIQUE KEY UK_BID_CASES_SEQ (SEQ_NO);

ALTER TABLE TASKS
    ADD COLUMN SEQ_NO BIGINT NOT NULL AUTO_INCREMENT,
    ADD UNIQUE KEY UK_TASKS_SEQ (SEQ_NO);
