server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
spring.datasource.jndi-name=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCL
spring.datasource.username=<LOCAL-DB-USER>
spring.datasource.password=<LOCAL-DB-PASSWORD>

upload.base-dir=C:/uploader-local

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.kb.uploader.domain
mybatis.configuration.map-underscore-to-camel-case=true

reclassification.cron=0 */5 * * * *

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
