spring.datasource.jndi-name=java:comp/env/jdbc/uploaderDS

upload.base-dir=/app/uploader

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.kb.uploader.domain
mybatis.configuration.map-underscore-to-camel-case=true

reclassification.cron=0 */5 * * * *
