server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
spring.datasource.jndi-name=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/uploaderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=<OUT-LOCAL-DB-PASSWORD>

upload.base-dir=C:/uploader-out-local

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.kb.uploader.domain
mybatis.configuration.map-underscore-to-camel-case=true

reclassification.cron=0 */5 * * * *

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
