--------------------------------------------------------------------------------
-- kgi-ggreport-web — Oracle 스키마 정본 (002) : 삽입 순서 컬럼 SEQ_NO
--
-- ⚠️ 이 파일이 **정본**이다. db/mysql/002_seq_no.sql 은 외부망 로컬 전용 미러다.
--
-- ── 왜 필요한가 ───────────────────────────────────────────────────────────────
-- Python 원본(server/)의 조회 SQL 8곳이 **SQLite 의 `rowid` = 삽입 순서**라는 성질에
-- 기대고 있다. Oracle 의 `ROWID` 는 삽입 순서가 아니라 **행의 물리 주소**라서 그대로
-- 옮기면 예외 없이 **조용히 틀린 답**이 나온다(행이 갱신·이동하면 순서가 바뀐다).
-- 단계 2 골든 시나리오는 기관당 공고가 1건뿐이라 `MAX(...)` 가 무의미하게 통과하므로
-- **골든 비교로도 잡히지 않는다.**
--
--   BID_CASES 5곳 : bidcase_repository.list_latest_bid_cases · consistency.check_all
--                   · orchestrator_service._latest_bid_case · routers/workflow.py 2곳
--   TASKS     3곳 : routers/tasks.py 2곳(ORDER BY rowid) · routers/approvals.py 1곳
--
-- ── 왜 IDENTITY 인가 ──────────────────────────────────────────────────────────
-- Oracle `GENERATED BY DEFAULT AS IDENTITY` ↔ MySQL `AUTO_INCREMENT` 로 두면
-- **INSERT 문이 양쪽에서 동일**하다(둘 다 컬럼을 생략하면 DB 가 채운다). 그래서
-- Mapper XML 이 한 벌로 끝나고 `databaseIdProvider` 가 필요 없다.
--
-- 검토했다 버린 안: LAST_SYNCED_AT 으로 "최신"을 판정 — DDL 변경은 0건이지만
-- **재수집이 순서를 뒤집고**(옛 공고가 최신이 된다) 동시각 타이가 여러 행을 돌려준다.
-- 이관의 기준은 "동작 동일"이므로 채택하지 않았다.
--
-- ⚠️ **Oracle 12c 이상을 전제한다.** 11g 에는 IDENTITY 가 없으므로 아래 파일 끝의
--    "11g 폴백" 절을 대신 쓴다(시퀀스 + BEFORE INSERT 트리거). 어느 쪽이든 앱에서
--    보이는 동작 — INSERT 때 SEQ_NO 를 안 넘기면 단조 증가값이 붙는다 — 은 같다.
--
-- ⚠️ 001 과 마찬가지로 **멱등하지 않다.** 빈 스키마에 001 을 적용한 직후 한 번만 돌린다.
--    (기존 데이터가 있는 테이블에 IDENTITY 컬럼을 추가하면 Oracle 이 기존 행을
--     채워 주기는 하지만 그 순서는 보장되지 않는다. 실데이터가 있는 상태에서
--     적용해야 한다면 순서를 사람이 정해 UPDATE 로 채운 뒤 IDENTITY 로 바꿔야 한다.)
--------------------------------------------------------------------------------

ALTER TABLE BID_CASES ADD (
    SEQ_NO NUMBER GENERATED BY DEFAULT AS IDENTITY
);

-- UNIQUE 는 조회 성능이 아니라 **계약**이다. `BY DEFAULT` 라서 앱이 값을 직접 넣을
-- 수도 있는데(시드·데이터 이관), 그때 중복이 들어가면 "최신 1건" 질의가 여러 행을
-- 돌려준다. MySQL 미러는 AUTO_INCREMENT 가 키를 요구해 어차피 UNIQUE 를 두므로
-- 여기에도 두어야 양쪽 제약이 같아진다.
ALTER TABLE BID_CASES ADD CONSTRAINT UK_BID_CASES_SEQ UNIQUE (SEQ_NO);

ALTER TABLE TASKS ADD (
    SEQ_NO NUMBER GENERATED BY DEFAULT AS IDENTITY
);

ALTER TABLE TASKS ADD CONSTRAINT UK_TASKS_SEQ UNIQUE (SEQ_NO);


--------------------------------------------------------------------------------
-- 11g 폴백 (12c 이상이면 이 절은 쓰지 않는다)
--
-- 위 4개 문장 대신 아래를 쓴다. 앱에서 보이는 동작은 같다 — INSERT 가 SEQ_NO 를
-- 넘기지 않으면 트리거가 시퀀스 값을 채운다(`GENERATED BY DEFAULT` 와 같은 의미로
-- 두려고 WHEN 절에 NULL 검사를 넣는다).
--
--   ALTER TABLE BID_CASES ADD (SEQ_NO NUMBER);
--   ALTER TABLE BID_CASES ADD CONSTRAINT UK_BID_CASES_SEQ UNIQUE (SEQ_NO);
--   CREATE SEQUENCE SEQ_BID_CASES START WITH 1 INCREMENT BY 1 NOCACHE;
--   CREATE OR REPLACE TRIGGER TRG_BID_CASES_SEQ
--       BEFORE INSERT ON BID_CASES FOR EACH ROW
--       WHEN (NEW.SEQ_NO IS NULL)
--   BEGIN
--       SELECT SEQ_BID_CASES.NEXTVAL INTO :NEW.SEQ_NO FROM DUAL;
--   END;
--   /
--
--   (TASKS 도 같은 모양으로 SEQ_TASKS · TRG_TASKS_SEQ 를 만든다.)
--------------------------------------------------------------------------------
