--------------------------------------------------------------------------------
-- kgi-ggreport-web — Oracle 스키마 정본 (005) : NOTIFICATIONS·MESSAGES 에도 SEQ_NO
--
-- ⚠️ 이 파일이 **정본**이다. db/mysql/005_seq_no_log_tables.sql 은 외부망 로컬 미러다.
--
-- ── 왜 또 SEQ_NO 인가 ────────────────────────────────────────────────────────
-- 002 와 **같은 결함의 다른 자리**다. 002 는 "최신 1건"을 rowid 로 고르던 8곳을
-- 고쳤고, 여기는 **같은 시각에 찍힌 줄들의 순서**다.
--
-- 타임라인(`GET /institutions/{id}/timeline`)은 쪽지와 작업 메시지를 한 줄기로 합쳐
-- `created_at` 으로 정렬한다. Python 은 **안정 정렬**이라 시각이 같으면 DB 가 준
-- 순서(= SQLite 삽입 순서)가 그대로 유지됐다. 시각이 마이크로초라 실제로 같아지는
-- 일도 드물었다.
--
-- Java 로 옮기면 두 전제가 다 약해진다:
--   ⓐ JDK 8 의 `Instant.now()` 는 보통 **밀리초**까지다(원본은 마이크로초).
--   ⓑ Oracle 은 `ORDER BY` 가 정하지 않은 순서를 **보장하지 않는다.**
--
-- ⚠️ **아직 관측된 실패는 아니다 — 대비다.** 단계 4-③ 시나리오를 실측하니 쪽지 4건이
--    11~42ms 간격이라 지금은 동률이 안 난다. 그러나 오케스트레이터(단계 4 후반)가
--    한 노드에서 메시지를 연달아 남기기 시작하면 밀리초 동률은 충분히 생기고,
--    그때 증상은 "타임라인 순서가 가끔 뒤섞인다"라 원인을 찾기 어렵다.
--    골든 29 가 그 순서를 계약으로 고정하고 있어 테스트도 간헐 실패로 나타난다.
--
-- 002 와 같은 처방을 쓴다: 삽입 순서 컬럼을 두고 `ORDER BY CREATED_AT, SEQ_NO` 로
-- 동률을 가른다. INSERT 문은 양쪽 방언에서 그대로다(컬럼을 생략하면 DB 가 채운다).
--
-- ⚠️ **Oracle 12c 이상을 전제한다** — 11g 폴백은 002 파일 끝의 절과 같은 모양이다.
-- ⚠️ 001·002 와 마찬가지로 **멱등하지 않다.** 한 번만 돌린다.
--------------------------------------------------------------------------------

ALTER TABLE NOTIFICATIONS ADD (
    SEQ_NO NUMBER GENERATED BY DEFAULT AS IDENTITY
);

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT UK_NOTIFICATIONS_SEQ UNIQUE (SEQ_NO);

ALTER TABLE MESSAGES ADD (
    SEQ_NO NUMBER GENERATED BY DEFAULT AS IDENTITY
);

ALTER TABLE MESSAGES ADD CONSTRAINT UK_MESSAGES_SEQ UNIQUE (SEQ_NO);
