-- =====================================================================
-- 007_uploader.sql — uploader 모듈 테이블의 Oracle 이식 (초안)
--
-- ⚠️ 아직 적용하지 않는다. 단계 6(uploader 붙이기)은 "이관 완료 후"로
--    확정돼 있다(2026-08-25 사용자 확정). 이 파일은 그때 쓸 초안이고,
--    아래 [결정 필요] 를 정하기 전에는 확정본이 아니다.
--
-- 원본: uploader/database_table 생성query.txt (MySQL 전용)
-- 매퍼: uploader/src/main/resources/mapper/{Institution,UploadedFile}Mapper.xml
--
-- MySQL → Oracle 로 바꾼 것 4가지:
--   1. BIGINT AUTO_INCREMENT → NUMBER GENERATED BY DEFAULT AS IDENTITY
--      ⚠️ Oracle 12c 이상 전제다(본체 002 와 같은 방식). 11g 면 시퀀스+트리거로
--         대체한다 — 문의 4(Oracle 버전) 회신이 확정한다. 폴백은 파일 끝 주석.
--   2. VARCHAR(n) → VARCHAR2(n CHAR)
--      ⚠️ CHAR 단위를 명시한다. 안 하면 NLS 설정에 따라 바이트 단위가 되어
--         한글 기관명이 200자가 아니라 66자에서 잘린다.
--   3. DATETIME → VARCHAR2(40 CHAR) ISO 문자열
--      ⚠️ 본체가 시각을 전부 문자열로 저장하기 때문이다(설계 §5). 타입을 섞으면
--         두 모듈의 시각을 한 정렬에 태울 수 없고, 004 가 30→40자로 넓힌 이유
--         (마이크로초+오프셋)도 그대로 적용된다.
--   4. ENGINE=InnoDB / DEFAULT CHARSET=utf8mb4 절 제거 (Oracle 에 없다)
--
-- ---------------------------------------------------------------------
-- [결정 필요] INSTITUTION(uploader) vs INSTITUTIONS(본체)
--
--   같은 개념인데 키 체계가 다르다:
--     uploader: ID BIGINT 자동증가 + NAME('도봉구')
--     본체    : INSTITUTION_ID VARCHAR2 문자열키('dobong') + NAME_KO('도봉구')
--
--   ⓐ 병존 (이 파일이 택한 안) — uploader 테이블을 그대로 옮긴다.
--      · 장점: uploader 코드를 한 줄도 안 고친다. 단계 6 이 가벼워진다.
--      · 단점: 기관 목록이 두 벌이 된다. 한쪽에만 기관을 추가하면 조용히 갈린다.
--   ⓑ 본체 참조 — UPLOADER_FILE 이 본체 INSTITUTIONS.INSTITUTION_ID 를 FK 로 본다.
--      · 장점: 진실이 하나. 기관명이 바뀌어도 안 끊긴다.
--      · 단점: uploader 의 매퍼·서비스를 고쳐야 하고, 업로드 시점에 기관명을
--        문자열키로 해석하는 자리가 새로 필요하다(이름→id 매핑 실패 처리 포함).
--
--   → ⓑ 를 고르면 아래 INSTITUTION 테이블을 통째로 지우고,
--      UPLOADED_FILE.INSTITUTION_NAME 을 INSTITUTION_ID 로 바꿔 FK 를 건다.
-- =====================================================================

-- ── 업로드된 파일 ────────────────────────────────────────────────────
CREATE TABLE UPLOADED_FILE (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ORIGINAL_NAME    VARCHAR2(500 CHAR)  NOT NULL,
    STORED_PATH      VARCHAR2(1000 CHAR) NOT NULL,
    FILE_YEAR        VARCHAR2(4 CHAR),
    -- ⚠️ FK 가 아니라 **이름 문자열**이다(원본 그대로). 기관명이 바뀌면 오류 없이
    --    조용히 끊긴다. ⓑ 안을 고르면 이 열이 INSTITUTION_ID FK 가 된다.
    INSTITUTION_NAME VARCHAR2(200 CHAR),
    CATEGORY         VARCHAR2(100 CHAR),
    STATUS           VARCHAR2(20 CHAR)   DEFAULT 'UNCLASSIFIED' NOT NULL,
    -- ISO 문자열(본체와 같은 모양). 예: 2026-08-28T06:12:33.481000+00:00
    UPLOADED_AT      VARCHAR2(40 CHAR)   NOT NULL,
    CLASSIFIED_AT    VARCHAR2(40 CHAR),
    CONSTRAINT PK_UPLOADED_FILE PRIMARY KEY (ID)
);

-- 분류 대기 목록이 첫 화면이라 STATUS 로 자주 거른다.
CREATE INDEX IDX_UPLOADED_FILE_STATUS ON UPLOADED_FILE (STATUS);
-- 기관별 조회.
CREATE INDEX IDX_UPLOADED_FILE_INST ON UPLOADED_FILE (INSTITUTION_NAME);

-- ── 기관 (⚠️ ⓑ 안을 고르면 이 테이블은 만들지 않는다) ────────────────
CREATE TABLE INSTITUTION (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NAME        VARCHAR2(200 CHAR) NOT NULL,
    CATEGORY    VARCHAR2(100 CHAR) NOT NULL,
    MODIFIED_AT VARCHAR2(40 CHAR)  NOT NULL,
    CONSTRAINT PK_INSTITUTION PRIMARY KEY (ID),
    CONSTRAINT UK_INSTITUTION_NAME UNIQUE (NAME)
);

-- =====================================================================
-- Oracle 11g 폴백 (IDENTITY 미지원)
--
--   CREATE SEQUENCE SEQ_UPLOADED_FILE START WITH 1 INCREMENT BY 1 NOCACHE;
--   CREATE OR REPLACE TRIGGER TRG_UPLOADED_FILE_ID
--     BEFORE INSERT ON UPLOADED_FILE FOR EACH ROW
--     WHEN (NEW.ID IS NULL)
--   BEGIN
--     :NEW.ID := SEQ_UPLOADED_FILE.NEXTVAL;
--   END;
--   / (INSTITUTION 도 같은 모양으로 하나 더)
--
--   ⚠️ 폴백을 쓰면 INSERT 문은 그대로여도 되지만, 매퍼가 생성 키를 돌려받는
--      방식(useGeneratedKeys)이 달라진다 — selectKey 로 바꿔야 한다.
-- =====================================================================
